### ISSUE TITLE
Задание для Светы

### ISSUE THREAD

**Issue by tiranderel** [tiranderel/DataBase-server#1]
Свет, начинаем делать проект по информатике! Твоя задача написать фрагмент кода, который состоит из 3-х функций. 1) Прочитать из файла все данные о ранее созданных таблицах (ее имя и кол-во полей) и сохранить это все в структуру с именем tables 2) Написать функцию, которой в качестве параметра передаётся имя новой таблицы и количество столбцов в ней. Затем эта информация добавляется в tables, и сохраняется файл.

**Comment by Svetoslavna** [comment]
Сделано
